language: python
python:
  - "2.6"
  #- "2.7"
  #- "3.2"
  #- "3.2"
  #- "3.2"
matrix:
  include:
    - python: 2.6
      env:
        - KUBE_TEST_API_VERSIONS=v1beta1 KUBE_TEST_ETCD_PREFIXES=registry
    - python: 2.7
      env:
        - KUBE_TEST_API_VERSIONS=v1beta3 KUBE_TEST_ETCD_PREFIXES=kubernetes.io/registry
install: python setup.py build
script:
  - python setup.py test
  #- sleep 12000s
#build_image: shippable/minv2
build_image: gcr.io/shippabledev/ubuntu1204_nodejs:latest
commit_container: gcr.io/shippabledev/shipgcrdemp
#commit_container: ragster/rags
cache: true
